### PR TITLE
Load class(es) with PSR-4

### PR DESCRIPTION
**Pull request by szepeviktor**
Introduce namespaces and `src/Site.php` becomes a clean class without side effects.

### CODE REVIEW

**Comment by szepeviktor** [comment]
kép

**Comment by szepeviktor** [comment]
😿 `45NorthVentures` is a not a valid vendor name.
What do you use in your PHP projects?

**Comment by szepeviktor** [comment]
@aedontanner What is the situation here? No PSR-4 for this project?

**Comment by aedontanner** [comment]
Sorry, GitHub auto-closed this when I moved branches. My mistake.  
Looks like I can't reopen, so I pretty much copied your PR over to the `refactor-dev` branch. Let me know if it looks alright.

**Comment by szepeviktor** [comment]
All right.
Please consider sparing one directory level as `src` has no files.
```json
        "psr-4": {
            "Jackpine\\": "src/"
        }
```

**Comment by aedontanner** [comment]
Seems like that's what most people are doing. Done.

**Pull request closed without merging**
